package net.tabor.seedcity.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Generated by tools/build_builder_assets.py; edit the source, then regenerate. */
public final class BuilderMesh {
    private BuilderMesh() {}
    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
		PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
				.texOffs(0, 0).addBox(-2F, -5F, -2F, 4F, 3F, 4F) // neck_joint
				.texOffs(18, 0).addBox(-4F, -2F, -2.5F, 8F, 7F, 5F) // torso
				.texOffs(46, 0).addBox(-3F, -2F, -3.5F, 6F, 5F, 1F) // chest_plate
				.texOffs(62, 0).addBox(-2F, -1F, -3.8F, 4F, 3F, 1F) // chest_inset
				.texOffs(74, 0).addBox(-0.5F, 0F, -4F, 1F, 1F, 1F) // chest_rune
				.texOffs(80, 0).addBox(-3F, -2F, 2.5F, 6F, 5F, 1F) // back_plate
				.texOffs(96, 0).addBox(-4.5F, 4F, -3F, 9F, 2F, 6F, new CubeDeformation(0.04F)) // belt
				.texOffs(128, 0).addBox(-1.5F, 4F, -4F, 3F, 2F, 1F) // buckle
				.texOffs(138, 0).addBox(-0.5F, 4.5F, -4.2F, 1F, 1F, 1F) // buckle_center
				.texOffs(144, 0).addBox(-3.5F, 6F, -2F, 7F, 1F, 4F) // hip_joint
				.texOffs(168, 0).addBox(2F, -3F, -4F, 1F, 7F, 1F, new CubeDeformation(0.04F)) // strap_front
				.texOffs(174, 0).addBox(2F, -3F, 3F, 1F, 7F, 1F, new CubeDeformation(0.04F)) // strap_back
				.texOffs(180, 0).addBox(2F, -3F, -3F, 1F, 1F, 6F) // strap_over_shoulder
				.texOffs(196, 0).addBox(1.5F, -1F, -4.3F, 2F, 2F, 1F, new CubeDeformation(0.08F)) // strap_clasp
				.texOffs(204, 0).addBox(2F, 5F, -4F, 3F, 3F, 2F) // pouch_left
				.texOffs(216, 0).addBox(-5F, 5F, -4F, 3F, 3F, 2F) // pouch_right
				.texOffs(228, 0).addBox(2F, 5F, -4.3F, 3F, 1F, 1F, new CubeDeformation(0.04F)) // pouch_flap_left
				.texOffs(238, 0).addBox(-5F, 5F, -4.3F, 3F, 1F, 1F, new CubeDeformation(0.04F)) // pouch_flap_right
				.texOffs(248, 0).addBox(-5F, 2F, 2F, 1F, 6F, 1F) // hammer_handle
				.texOffs(0, 14).addBox(-6F, 1F, 1.5F, 3F, 2F, 2F) // hammer_head
				, PartPose.offset(0F, 10F, 0F));
		PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create()
				.texOffs(12, 14).addBox(-3.5F, -6F, -3F, 7F, 6F, 6F) // head_shell
				.texOffs(40, 14).addBox(-4F, -6F, -3.5F, 8F, 2F, 7F, new CubeDeformation(0.04F)) // brow
				.texOffs(72, 14).addBox(-3F, -4F, -3.15F, 6F, 3F, 1F) // visor_recess
				.texOffs(88, 14).addBox(-2F, -3.5F, -3.3F, 1F, 2F, 1F) // right_eye
				.texOffs(94, 14).addBox(1F, -3.5F, -3.3F, 1F, 2F, 1F) // left_eye
				.texOffs(100, 14).addBox(-0.5F, -4F, -3.6F, 1F, 3F, 1F, new CubeDeformation(0.04F)) // nose_bridge
				.texOffs(106, 14).addBox(-3.5F, -1F, -3.5F, 7F, 1F, 6F, new CubeDeformation(0.04F)) // jaw
				.texOffs(134, 14).addBox(-4F, -4F, -0.5F, 1F, 3F, 3F) // right_temple
				.texOffs(144, 14).addBox(3F, -4F, -0.5F, 1F, 3F, 3F) // left_temple
				, PartPose.offset(0F, -4F, 0F));
		PartDefinition right_arm = body.addOrReplaceChild("right_arm", CubeListBuilder.create()
				.texOffs(154, 14).addBox(-2F, -1F, -2.5F, 4F, 4F, 5F) // right_shoulder
				.texOffs(174, 14).addBox(-2F, 2F, -2.6F, 4F, 1F, 5F, new CubeDeformation(0.04F)) // right_shoulder_band
				.texOffs(194, 14).addBox(-1F, 3F, -1.5F, 2F, 2F, 3F) // right_elbow
				.texOffs(206, 14).addBox(-1.5F, 5F, -2F, 3F, 3F, 4F) // right_forearm
				.texOffs(222, 14).addBox(-1.5F, 7F, -2.2F, 3F, 1F, 4F, new CubeDeformation(0.04F)) // right_cuff
				.texOffs(238, 14).addBox(-1.5F, 8F, -2F, 3F, 2F, 3F) // right_hand
				, PartPose.offset(-6F, -2F, 0F));
		PartDefinition left_arm = body.addOrReplaceChild("left_arm", CubeListBuilder.create()
				.texOffs(80, 28).addBox(-2F, -1F, -2.5F, 4F, 4F, 5F) // left_shoulder
				.texOffs(100, 28).addBox(-2F, 2F, -2.6F, 4F, 1F, 5F, new CubeDeformation(0.04F)) // left_shoulder_band
				.texOffs(120, 28).addBox(-1F, 3F, -1.5F, 2F, 2F, 3F) // left_elbow
				.texOffs(132, 28).addBox(-1.5F, 5F, -2F, 3F, 3F, 4F) // left_forearm
				.texOffs(148, 28).addBox(-1.5F, 7F, -2.2F, 3F, 1F, 4F, new CubeDeformation(0.04F)) // left_cuff
				.texOffs(164, 28).addBox(-1.5F, 8F, -2F, 3F, 2F, 3F) // left_hand
				, PartPose.offset(6F, -2F, 0F));
		PartDefinition right_leg = body.addOrReplaceChild("right_leg", CubeListBuilder.create()
				.texOffs(0, 28).addBox(-1.5F, 0F, -1.5F, 3F, 3F, 3F) // right_thigh
				.texOffs(14, 28).addBox(-1.5F, 3F, -2F, 3F, 2F, 3F) // right_knee
				.texOffs(28, 28).addBox(-1.5F, 4F, -2F, 3F, 3F, 4F, new CubeDeformation(0.04F)) // right_shin
				.texOffs(44, 28).addBox(-2F, 7F, -3F, 4F, 1F, 5F) // right_boot
				.texOffs(64, 28).addBox(-1.5F, 4F, -2.2F, 3F, 1F, 4F, new CubeDeformation(0.08F)) // right_boot_cuff
				, PartPose.offset(-2.4F, 6F, 0F));
		PartDefinition left_leg = body.addOrReplaceChild("left_leg", CubeListBuilder.create()
				.texOffs(178, 28).addBox(-1.5F, 0F, -1.5F, 3F, 3F, 3F) // left_thigh
				.texOffs(192, 28).addBox(-1.5F, 3F, -2F, 3F, 2F, 3F) // left_knee
				.texOffs(206, 28).addBox(-1.5F, 4F, -2F, 3F, 3F, 4F, new CubeDeformation(0.04F)) // left_shin
				.texOffs(222, 28).addBox(-2F, 7F, -3F, 4F, 1F, 5F) // left_boot
				.texOffs(0, 39).addBox(-1.5F, 4F, -2.2F, 3F, 1F, 4F, new CubeDeformation(0.08F)) // left_boot_cuff
				, PartPose.offset(2.4F, 6F, 0F));
		PartDefinition cargo = right_arm.addOrReplaceChild("cargo", CubeListBuilder.create()
				.texOffs(16, 39).addBox(-2.5F, -2.5F, -2.5F, 5F, 5F, 5F) // carried_stone
				, PartPose.offset(0F, 7F, -4F));
        return LayerDefinition.create(mesh, 256, 256);
    }
}
