package net.tabor.seedcity.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Generated by tools/build_collector_assets.py; edit the source, then regenerate. */
public final class CollectorMesh {
    private CollectorMesh() {}
    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
		PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
				, PartPose.offset(0F, 24F, 0F));
		PartDefinition torso = body.addOrReplaceChild("torso", CubeListBuilder.create()
				.texOffs(0, 0).addBox(4.6F, -5F, 7.5F, 1F, 4F, 3F, new CubeDeformation(0.012F)) // lantern_mount_plate
				.texOffs(10, 0).addBox(5.45F, -4.6F, 8.5F, 1F, 1F, 1F, new CubeDeformation(0.0125F)) // lantern_mount_rivet_top
				.texOffs(16, 0).addBox(5.45F, -2.5F, 8.5F, 1F, 1F, 1F, new CubeDeformation(0.013F)) // lantern_mount_rivet_bottom
				.texOffs(22, 0).addBox(5F, -3.75F, 8.5F, 3F, 1F, 1F, new CubeDeformation(0.0135F)) // lantern_bracket_arm
				.texOffs(32, 0).addBox(5F, -2.5F, 8.5F, 1F, 1F, 1F, new CubeDeformation(0.014F)) // lantern_bracket_brace_lower
				.texOffs(38, 0).addBox(5.8F, -3.05F, 8.5F, 1F, 1F, 1F, new CubeDeformation(0.0145F)) // lantern_bracket_brace_upper
				.texOffs(162, 0).addBox(-5F, 0F, -3F, 10F, 11F, 7F, new CubeDeformation(0.0205F)) // torso
				.texOffs(198, 0).addBox(-4F, 2F, -3.5F, 8F, 7F, 1F, new CubeDeformation(0.021F)) // apron
				.texOffs(218, 0).addBox(-3F, 3F, -3.7F, 6F, 4F, 1F, new CubeDeformation(0.0215F)) // apron_center
				.texOffs(0, 20).addBox(-5F, 9F, -3.5F, 10F, 2F, 8F, new CubeDeformation(0.022F)) // belt
				.texOffs(38, 20).addBox(-1F, 9F, -3.8F, 2F, 2F, 1F, new CubeDeformation(0.0225F)) // belt_buckle
				.texOffs(46, 20).addBox(-5F, -5F, 4F, 10F, 15F, 5F, new CubeDeformation(0.023F)) // pack
				.texOffs(78, 20).addBox(-5F, -6F, 4F, 10F, 2F, 5F, new CubeDeformation(0.0235F)) // pack_rim
				.texOffs(110, 20).addBox(-4F, -4F, 8.5F, 1F, 14F, 1F, new CubeDeformation(0.024F)) // pack_strap_right
				.texOffs(116, 20).addBox(3F, -4F, 8.5F, 1F, 14F, 1F, new CubeDeformation(0.0245F)) // pack_strap_left
				.texOffs(122, 20).addBox(-5F, 9F, 4F, 10F, 2F, 5F, new CubeDeformation(0.025F)) // pack_bottom
				.texOffs(154, 20).addBox(-4F, -11F, 4F, 5F, 6F, 4F, new CubeDeformation(0.0255F)) // stone_cargo
				.texOffs(174, 20).addBox(-3F, -13F, 5F, 3F, 2F, 3F, new CubeDeformation(0.026F)) // stone_cargo_top
				.texOffs(188, 20).addBox(1F, -12F, 4F, 3F, 7F, 4F, new CubeDeformation(0.0265F)) // log_cargo
				.texOffs(204, 20).addBox(1F, -12.1F, 4F, 3F, 1F, 4F, new CubeDeformation(0.027F)) // log_cut_end
				.texOffs(220, 20).addBox(0F, -8F, 7F, 4F, 3F, 3F, new CubeDeformation(0.0275F)) // log_cargo_short
				, PartPose.offset(0F, -21F, 0F));
		PartDefinition head = torso.addOrReplaceChild("head", CubeListBuilder.create()
				.texOffs(0, 42).addBox(-4F, -8F, -4F, 8F, 8F, 8F, new CubeDeformation(0.028F)) // helmet
				.texOffs(34, 42).addBox(-4F, -8.1F, -4F, 8F, 2F, 8F, new CubeDeformation(0.0285F)) // helmet_crown
				.texOffs(68, 42).addBox(-4.5F, -6.5F, -4.5F, 9F, 1F, 9F, new CubeDeformation(0.029F)) // helmet_brim
				.texOffs(106, 42).addBox(-3.5F, -5.5F, -4.08F, 7F, 4F, 1F, new CubeDeformation(0.0295F)) // face_inset
				.texOffs(124, 42).addBox(-3F, -4.75F, -4.16F, 2F, 2F, 1F, new CubeDeformation(0.03F)) // eye_right
				.texOffs(132, 42).addBox(1F, -4.75F, -4.16F, 2F, 2F, 1F, new CubeDeformation(0.0305F)) // eye_left
				.texOffs(140, 42).addBox(-2F, -8F, -4.7F, 4F, 2F, 1F, new CubeDeformation(0.031F)) // lamp_bracket
				.texOffs(152, 42).addBox(-1.5F, -8F, -5F, 3F, 2F, 1F, new CubeDeformation(0.0315F)) // lamp_rim
				.texOffs(162, 42).addBox(-1F, -8F, -5.3F, 2F, 2F, 1F, new CubeDeformation(0.032F)) // lamp_light
				, PartPose.offset(0F, 0F, 0F));
		PartDefinition right_arm = torso.addOrReplaceChild("right_arm", CubeListBuilder.create()
				.texOffs(170, 42).addBox(-2F, -1F, -2F, 4F, 4F, 5F, new CubeDeformation(0.0325F)) // right_shoulder
				.texOffs(190, 42).addBox(-1.5F, 3F, -1.5F, 3F, 4F, 3F, new CubeDeformation(0.033F)) // right_upper_arm
				.texOffs(204, 42).addBox(-2F, 6F, -2F, 4F, 5F, 4F, new CubeDeformation(0.0335F)) // right_gauntlet
				.texOffs(222, 42).addBox(-1.5F, 10F, -1.5F, 3F, 3F, 3F, new CubeDeformation(0.034F)) // right_hand
				, PartPose.offset(-7F, 1F, 0F));
		PartDefinition left_arm = torso.addOrReplaceChild("left_arm", CubeListBuilder.create()
				.texOffs(236, 42).addBox(-2F, -1F, -2F, 4F, 4F, 5F, new CubeDeformation(0.0345F)) // left_shoulder
				.texOffs(0, 60).addBox(-1.5F, 3F, -1.5F, 3F, 4F, 3F, new CubeDeformation(0.035F)) // left_upper_arm
				.texOffs(14, 60).addBox(-2F, 6F, -2F, 4F, 5F, 4F, new CubeDeformation(0.0355F)) // left_gauntlet
				.texOffs(32, 60).addBox(-1.5F, 10F, -1.5F, 3F, 3F, 3F, new CubeDeformation(0.036F)) // left_hand
				, PartPose.offset(7F, 1F, 0F));
		PartDefinition right_leg = body.addOrReplaceChild("right_leg", CubeListBuilder.create()
				.texOffs(46, 60).addBox(-2F, 0F, -2F, 4F, 5F, 4F, new CubeDeformation(0.0365F)) // right_thigh
				.texOffs(64, 60).addBox(-2F, 4F, -2F, 4F, 4F, 4F, new CubeDeformation(0.037F)) // right_shin
				.texOffs(82, 60).addBox(-2.5F, 8F, -3F, 5F, 2F, 6F, new CubeDeformation(0.0375F)) // right_boot
				, PartPose.offset(-3F, -10F, 0F));
		PartDefinition left_leg = body.addOrReplaceChild("left_leg", CubeListBuilder.create()
				.texOffs(106, 60).addBox(-2F, 0F, -2F, 4F, 5F, 4F, new CubeDeformation(0.038F)) // left_thigh
				.texOffs(124, 60).addBox(-2F, 4F, -2F, 4F, 4F, 4F, new CubeDeformation(0.0385F)) // left_shin
				.texOffs(142, 60).addBox(-2.5F, 8F, -3F, 5F, 2F, 6F, new CubeDeformation(0.039F)) // left_boot
				, PartPose.offset(3F, -10F, 0F));
		PartDefinition lantern = torso.addOrReplaceChild("lantern", CubeListBuilder.create()
				.texOffs(44, 0).addBox(-1.5F, -0.3F, -0.5F, 3F, 1F, 1F, new CubeDeformation(0.015F)) // lantern_bail_top
				.texOffs(54, 0).addBox(-1.5F, 0.5F, -0.5F, 1F, 3F, 1F, new CubeDeformation(0.0155F)) // lantern_bail_left
				.texOffs(60, 0).addBox(0.5F, 0.5F, -0.5F, 1F, 3F, 1F, new CubeDeformation(0.016F)) // lantern_bail_right
				.texOffs(66, 0).addBox(-2.5F, 3F, -2.5F, 5F, 1F, 5F, new CubeDeformation(0.0165F)) // lantern_cap
				.texOffs(88, 0).addBox(-1.5F, 2.5F, -1.5F, 3F, 1F, 3F, new CubeDeformation(0.017F)) // lantern_cap_crown
				.texOffs(102, 0).addBox(-1.5F, 4F, -1.5F, 3F, 4F, 3F, new CubeDeformation(0.0175F)) // lantern_light
				.texOffs(116, 0).addBox(-2.5F, 8F, -2.5F, 5F, 1F, 5F, new CubeDeformation(0.018F)) // lantern_base
				.texOffs(138, 0).addBox(-2.5F, 4F, -2.5F, 1F, 4F, 1F, new CubeDeformation(0.0185F)) // lantern_post_5_6.5
				.texOffs(144, 0).addBox(-2.5F, 4F, 1.5F, 1F, 4F, 1F, new CubeDeformation(0.019F)) // lantern_post_5_10.5
				.texOffs(150, 0).addBox(1.5F, 4F, -2.5F, 1F, 4F, 1F, new CubeDeformation(0.0195F)) // lantern_post_9_6.5
				.texOffs(156, 0).addBox(1.5F, 4F, 1.5F, 1F, 4F, 1F, new CubeDeformation(0.02F)) // lantern_post_9_10.5
				, PartPose.offset(7.5F, -3F, 9F).withScale(.7F));
        return LayerDefinition.create(mesh, 256, 256);
    }
}
