package net.tabor.seedcity.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Generated by tools/build_rectifier_assets.py; edit the source, then regenerate. */
public final class RectifierMesh {
    private RectifierMesh() {}
    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
		PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
				.texOffs(0, 0).addBox(-2F, -13F, -2F, 4F, 4F, 4F) // neck
				.texOffs(18, 0).addBox(-6F, -11F, -4F, 12F, 13F, 8F) // torso
				.texOffs(60, 0).addBox(-4F, -10F, -5F, 8F, 9F, 2F) // chest_rim
				.texOffs(82, 0).addBox(-3F, -9F, -5.4F, 6F, 7F, 1F, new CubeDeformation(0.02F)) // chest_socket
				.texOffs(98, 0).addBox(-2F, -8F, -5.65F, 4F, 5F, 1F) // core
				.texOffs(110, 0).addBox(-1F, -7F, -5.8F, 2F, 3F, 1F) // core_center
				.texOffs(118, 0).addBox(4F, -11F, -5.5F, 3F, 10F, 3F, new CubeDeformation(0.04F)) // chest_left
				.texOffs(132, 0).addBox(-7F, -11F, -5.5F, 3F, 10F, 3F, new CubeDeformation(0.04F)) // chest_right
				.texOffs(146, 0).addBox(-5F, -10F, 4F, 10F, 10F, 1F) // back_plate
				.texOffs(170, 0).addBox(-1F, -9F, 5F, 2F, 8F, 1F) // back_spine
				.texOffs(178, 0).addBox(-6F, 2F, -3.5F, 12F, 3F, 7F, new CubeDeformation(0.04F)) // belt
				.texOffs(218, 0).addBox(-2F, 1.5F, -5F, 4F, 3F, 2F, new CubeDeformation(0.06F)) // buckle
				.texOffs(0, 23).addBox(-3F, 4.2F, -2.4F, 6F, 2F, 5F) // hip
				.texOffs(100, 82).addBox(-4F, -10.5F, -5.7F, 8F, 1F, 1F, new CubeDeformation(0.03F)) // core_top_lip
				.texOffs(120, 82).addBox(-4F, -1.5F, -5.7F, 8F, 1F, 1F, new CubeDeformation(0.05F)) // core_lower_lip
				.texOffs(140, 82).addBox(-4.5F, -10.5F, -5.9F, 1F, 9F, 1F, new CubeDeformation(0.01F)) // chest_plate_inner_right
				.texOffs(146, 82).addBox(3.5F, -10.5F, -5.9F, 1F, 9F, 1F, new CubeDeformation(0.015F)) // chest_plate_inner_left
				.texOffs(152, 82).addBox(-6F, 0F, -4.5F, 3F, 2F, 2F, new CubeDeformation(0.015F)) // rib_right
				.texOffs(164, 82).addBox(3F, 0F, -4.5F, 3F, 2F, 2F, new CubeDeformation(0.025F)) // rib_left
				.texOffs(176, 82).addBox(-6F, 2.5F, -4.3F, 3F, 2F, 1F, new CubeDeformation(0.035F)) // waist_right
				.texOffs(186, 82).addBox(3F, 2.5F, -4.3F, 3F, 2F, 1F, new CubeDeformation(0.045F)) // waist_left
				.texOffs(196, 82).addBox(-5F, 2.8F, -4.5F, 1F, 1F, 1F, new CubeDeformation(0.005F)) // waist_pin_right
				.texOffs(202, 82).addBox(4F, 2.8F, -4.5F, 1F, 1F, 1F, new CubeDeformation(0.008F)) // waist_pin_left
				.texOffs(208, 82).addBox(-2F, 1F, -5.2F, 4F, 1F, 1F, new CubeDeformation(0.02F)) // belt_clasp_top
				.texOffs(202, 96).addBox(-4.8F, -10.5F, 3.5F, 2F, 2F, 4F) // cape_clasp_right
				.texOffs(216, 96).addBox(2.8F, -10.5F, 3.5F, 2F, 2F, 4F) // cape_clasp_left
				.texOffs(230, 96).addBox(-10.5F, -8.5F, -1.5F, 5F, 3F, 3F) // right_shoulder_axle
				.texOffs(0, 127).addBox(5.5F, -8.5F, -1.5F, 5F, 3F, 3F) // left_shoulder_axle
				, PartPose.offset(0F, -3F, 0F));
		PartDefinition cape = body.addOrReplaceChild("cape", CubeListBuilder.create()
				.texOffs(174, 96).addBox(-6F, 0F, 0F, 12F, 28F, 1F) // cape_cloth
				, PartPose.offset(0F, -10F, 6F));
		PartDefinition tabard = body.addOrReplaceChild("tabard", CubeListBuilder.create()
				.texOffs(232, 0).addBox(-2F, 0F, 0F, 4F, 14F, 1F) // tabard_trim
				.texOffs(244, 0).addBox(-1.5F, 0.5F, -0.2F, 3F, 13F, 1F) // tabard
				.texOffs(220, 82).addBox(-1.5F, 14F, 0F, 3F, 1F, 1F, new CubeDeformation(0.01F)) // cloth_tail
				, PartPose.offset(0F, 4F, -4.5F));
		PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create()
				.texOffs(24, 23).addBox(-4.5F, -9F, -4F, 9F, 9F, 8F) // helmet
				.texOffs(60, 23).addBox(-4.5F, -9F, -4.5F, 9F, 3F, 9F, new CubeDeformation(0.04F)) // crown
				.texOffs(98, 23).addBox(-3.5F, -6F, -4.2F, 7F, 4F, 1F) // face_shadow
				.texOffs(116, 23).addBox(-0.5F, -6F, -4.4F, 1F, 5F, 1F, new CubeDeformation(0.04F)) // vertical_visor
				.texOffs(122, 23).addBox(-4F, -5F, -4.5F, 3F, 5F, 1F, new CubeDeformation(0.06F)) // cheek_right
				.texOffs(132, 23).addBox(1F, -5F, -4.5F, 3F, 5F, 1F, new CubeDeformation(0.06F)) // cheek_left
				.texOffs(70, 82).addBox(-4.5F, -6.5F, -4.8F, 9F, 1F, 1F, new CubeDeformation(0.03F)) // brow_lip
				.texOffs(92, 82).addBox(-1F, -6F, -4.3F, 2F, 5F, 1F, new CubeDeformation(0.02F)) // visor_inner
				, PartPose.offset(0F, -11F, 0F));
		PartDefinition right_arm = body.addOrReplaceChild("right_arm", CubeListBuilder.create()
				.texOffs(142, 23).addBox(-3.5F, -6F, -3.5F, 7F, 8F, 7F) // right_shoulder
				.texOffs(172, 23).addBox(-2F, 2F, -2F, 4F, 6F, 4F) // right_upper_arm
				.texOffs(190, 23).addBox(-1.5F, 8F, -1.5F, 3F, 2F, 3F) // right_elbow
				.texOffs(230, 82).addBox(-2F, 3F, -2.5F, 4F, 4F, 1F, new CubeDeformation(0.02F)) // right_upper_arm_plate
				, PartPose.offset(-10F, -7F, 0F));
		PartDefinition left_arm = body.addOrReplaceChild("left_arm", CubeListBuilder.create()
				.texOffs(142, 42).addBox(-3.5F, -6F, -3.5F, 7F, 8F, 7F) // left_shoulder
				.texOffs(172, 42).addBox(-2F, 2F, -2F, 4F, 6F, 4F) // left_upper_arm
				.texOffs(190, 42).addBox(-1.5F, 8F, -1.5F, 3F, 2F, 3F) // left_elbow
				.texOffs(68, 96).addBox(-2F, 3F, -2.5F, 4F, 4F, 1F, new CubeDeformation(0.02F)) // left_upper_arm_plate
				, PartPose.offset(10F, -7F, 0F));
		PartDefinition right_leg = body.addOrReplaceChild("right_leg", CubeListBuilder.create()
				.texOffs(0, 42).addBox(-3F, 0F, -3F, 6F, 12F, 6F) // right_thigh
				.texOffs(26, 42).addBox(-2.5F, 11F, -2.5F, 5F, 2F, 5F) // right_knee
				.texOffs(48, 42).addBox(-3.5F, 16F, -3.5F, 7F, 5F, 7F) // right_greave
				.texOffs(78, 42).addBox(-3.5F, 13F, -3.5F, 7F, 3F, 7F) // right_greave_band
				.texOffs(108, 42).addBox(-4F, 21F, -4.5F, 8F, 2F, 8F) // right_boot
				.texOffs(16, 96).addBox(-2.5F, 16.5F, -3.7F, 5F, 4F, 1F, new CubeDeformation(0.01F)) // right_shin_panel
				.texOffs(30, 96).addBox(-3.5F, 20F, -3.6F, 7F, 1F, 1F, new CubeDeformation(0.03F)) // right_ankle_trim
				.texOffs(48, 96).addBox(-4F, 21F, -4.7F, 8F, 1F, 1F, new CubeDeformation(0.02F)) // right_toe_cap
				, PartPose.offset(-5F, 4F, 0F));
		PartDefinition left_leg = body.addOrReplaceChild("left_leg", CubeListBuilder.create()
				.texOffs(0, 62).addBox(-3F, 0F, -3F, 6F, 12F, 6F) // left_thigh
				.texOffs(26, 62).addBox(-2.5F, 11F, -2.5F, 5F, 2F, 5F) // left_knee
				.texOffs(48, 62).addBox(-3.5F, 16F, -3.5F, 7F, 5F, 7F) // left_greave
				.texOffs(78, 62).addBox(-3.5F, 13F, -3.5F, 7F, 3F, 7F) // left_greave_band
				.texOffs(108, 62).addBox(-4F, 21F, -4.5F, 8F, 2F, 8F) // left_boot
				.texOffs(122, 96).addBox(-2.5F, 16.5F, -3.7F, 5F, 4F, 1F, new CubeDeformation(0.01F)) // left_shin_panel
				.texOffs(136, 96).addBox(-3.5F, 20F, -3.6F, 7F, 1F, 1F, new CubeDeformation(0.03F)) // left_ankle_trim
				.texOffs(154, 96).addBox(-4F, 21F, -4.7F, 8F, 1F, 1F, new CubeDeformation(0.02F)) // left_toe_cap
				, PartPose.offset(5F, 4F, 0F));
		PartDefinition right_forearm = right_arm.addOrReplaceChild("right_forearm", CubeListBuilder.create()
				.texOffs(204, 23).addBox(-3F, -1F, -3F, 6F, 7F, 6F) // right_forearm
				.texOffs(230, 23).addBox(-2F, 5F, -2F, 4F, 3F, 4F) // right_hand
				.texOffs(0, 96).addBox(-3F, -1F, -3.5F, 6F, 2F, 1F, new CubeDeformation(0.03F)) // right_gauntlet_ridge
				, PartPose.offset(0F, 10F, 0F));
		PartDefinition lantern = right_forearm.addOrReplaceChild("lantern", CubeListBuilder.create()
				.texOffs(142, 62).addBox(-0.5F, 0F, -0.5F, 1F, 3F, 1F) // lantern_handle
				.texOffs(148, 62).addBox(-2.5F, 3F, -2.5F, 5F, 1F, 5F) // lantern_cap
				.texOffs(170, 62).addBox(-1.5F, 4F, -1.5F, 3F, 4F, 3F) // lantern_light
				.texOffs(184, 62).addBox(-2.5F, 8F, -2.5F, 5F, 1F, 5F) // lantern_base
				.texOffs(206, 62).addBox(-2.5F, 4F, -2.5F, 1F, 4F, 1F) // lantern_post_-11.5_-2.5
				.texOffs(212, 62).addBox(-2.5F, 4F, 1.5F, 1F, 4F, 1F) // lantern_post_-11.5_1.5
				.texOffs(218, 62).addBox(1.5F, 4F, -2.5F, 1F, 4F, 1F) // lantern_post_-7.5_-2.5
				.texOffs(224, 62).addBox(1.5F, 4F, 1.5F, 1F, 4F, 1F) // lantern_post_-7.5_1.5
				, PartPose.offset(0F, 7F, 0F));
		PartDefinition left_forearm = left_arm.addOrReplaceChild("left_forearm", CubeListBuilder.create()
				.texOffs(204, 42).addBox(-3F, -1F, -3F, 6F, 7F, 6F) // left_forearm
				.texOffs(230, 42).addBox(-2F, 5F, -2F, 4F, 3F, 4F) // left_hand
				.texOffs(80, 96).addBox(-3F, -1F, -3.5F, 6F, 2F, 1F, new CubeDeformation(0.03F)) // left_gauntlet_ridge
				.texOffs(96, 96).addBox(1.5F, 4F, -2.7F, 1F, 3F, 2F, new CubeDeformation(0.02F)) // left_thumb
				.texOffs(104, 96).addBox(-1.75F, 6F, -2.4F, 1F, 2F, 1F, new CubeDeformation(0.005F)) // left_finger_0
				.texOffs(110, 96).addBox(-0.5F, 6F, -2.4F, 1F, 2F, 1F, new CubeDeformation(0.01F)) // left_finger_1
				.texOffs(116, 96).addBox(0.75F, 6F, -2.4F, 1F, 2F, 1F, new CubeDeformation(0.015F)) // left_finger_2
				, PartPose.offset(0F, 10F, 0F));
		PartDefinition hammer = left_forearm.addOrReplaceChild("hammer", CubeListBuilder.create()
				.texOffs(230, 62).addBox(-1F, -7F, -1F, 2F, 16F, 2F, new CubeDeformation(-0.04F)) // hammer_handle
				.texOffs(240, 62).addBox(-1.5F, -4F, -1.5F, 3F, 4F, 3F, new CubeDeformation(0.04F)) // hammer_grip
				.texOffs(0, 82).addBox(-1.5F, -5F, -1.5F, 3F, 1F, 3F, new CubeDeformation(0.06F)) // hammer_collar
				.texOffs(14, 82).addBox(-2.5F, -9F, -4F, 5F, 4F, 8F) // hammer_head
				.texOffs(42, 82).addBox(-2.5F, -9F, -5F, 5F, 4F, 1F, new CubeDeformation(0.04F)) // hammer_striking_left
				.texOffs(56, 82).addBox(-2.5F, -9F, 4F, 5F, 4F, 1F, new CubeDeformation(0.04F)) // hammer_striking_right
				, PartPose.offset(0F, 7F, -1F));
        return LayerDefinition.create(mesh, 256, 256);
    }
}
