package net.tabor.seedcity.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Generated by tools/build_redstone_rat_assets.py; edit the source, then regenerate. */
public final class RedstoneRatMesh {
    private RedstoneRatMesh() {}
    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
		PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
				.texOffs(0, 0).addBox(-1F, -3.75F, -5.5F, 2F, 2F, 3F, new CubeDeformation(0.012F)) // neck
				, PartPose.offset(0F, 24F, 0F));
		PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create()
				, PartPose.offset(0F, -3.75F, -4F));
		PartDefinition segment_0 = head.addOrReplaceChild("segment_0", CubeListBuilder.create()
				.texOffs(12, 0).addBox(-1F, -1F, -1F, 2F, 2F, 2F, new CubeDeformation(0.0125F)) // segment_0
				.texOffs(114, 0).addBox(-0.5F, -0.7F, -1.3F, 1F, 1F, 1F, new CubeDeformation(0.016F)) // nose
				, PartPose.offset(0F, 1.25F, -4F));
		PartDefinition segment_1 = head.addOrReplaceChild("segment_1", CubeListBuilder.create()
				.texOffs(22, 0).addBox(-2F, -1.5F, -1.5F, 4F, 3F, 3F, new CubeDeformation(0.013F)) // segment_1
				.texOffs(120, 0).addBox(1.25F, -1F, -1.15F, 1F, 1F, 1F, new CubeDeformation(0.0165F)) // eye_left
				.texOffs(126, 0).addBox(-2.25F, -1F, -1.15F, 1F, 1F, 1F, new CubeDeformation(0.017F)) // eye_right
				.texOffs(132, 0).addBox(1F, -3.5F, 0F, 2F, 3F, 1F, new CubeDeformation(0.0175F)) // ear_left
				.texOffs(140, 0).addBox(1.45F, -2.8F, -0.15F, 1F, 2F, 1F, new CubeDeformation(0.018F)) // ear_inner_left
				.texOffs(146, 0).addBox(-3F, -3.5F, 0F, 2F, 3F, 1F, new CubeDeformation(0.0185F)) // ear_right
				.texOffs(154, 0).addBox(-2.55F, -2.8F, -0.15F, 1F, 2F, 1F, new CubeDeformation(0.019F)) // ear_inner_right
				, PartPose.offset(0F, 0.75F, -1.5F));
		PartDefinition segment_2 = body.addOrReplaceChild("segment_2", CubeListBuilder.create()
				.texOffs(38, 0).addBox(-2.5F, -2F, -1.5F, 5F, 4F, 3F, new CubeDeformation(0.0135F)) // segment_2
				, PartPose.offset(0F, -2.75F, -2.5F));
		PartDefinition segment_3 = body.addOrReplaceChild("segment_3", CubeListBuilder.create()
				.texOffs(56, 0).addBox(-3F, -2F, -1.5F, 6F, 4F, 3F, new CubeDeformation(0.014F)) // segment_3
				, PartPose.offset(0F, -2.75F, 0.5F));
		PartDefinition segment_4 = body.addOrReplaceChild("segment_4", CubeListBuilder.create()
				.texOffs(76, 0).addBox(-2.5F, -2F, -1.5F, 5F, 4F, 3F, new CubeDeformation(0.0145F)) // segment_4
				, PartPose.offset(0F, -2.75F, 3.5F));
		PartDefinition segment_5 = body.addOrReplaceChild("segment_5", CubeListBuilder.create()
				.texOffs(94, 0).addBox(-1.5F, -1.5F, -1F, 3F, 3F, 2F, new CubeDeformation(0.015F)) // segment_5
				, PartPose.offset(0F, -2.25F, 6F));
		PartDefinition segment_6 = body.addOrReplaceChild("segment_6", CubeListBuilder.create()
				.texOffs(106, 0).addBox(-0.5F, -0.5F, -1F, 1F, 1F, 2F, new CubeDeformation(0.0155F)) // segment_6
				, PartPose.offset(0F, -1.25F, 8F));
		PartDefinition paw_left_front = body.addOrReplaceChild("paw_left_front", CubeListBuilder.create()
				.texOffs(160, 0).addBox(-0.5F, 0F, -1F, 1F, 1F, 2F, new CubeDeformation(0.0195F)) // paw_left_front
				, PartPose.offset(2.25F, -1F, -2F));
		PartDefinition paw_left_back = body.addOrReplaceChild("paw_left_back", CubeListBuilder.create()
				.texOffs(168, 0).addBox(-0.5F, 0F, -1F, 1F, 1F, 2F, new CubeDeformation(0.02F)) // paw_left_back
				, PartPose.offset(2.25F, -1F, 4F));
		PartDefinition paw_right_front = body.addOrReplaceChild("paw_right_front", CubeListBuilder.create()
				.texOffs(176, 0).addBox(-0.5F, 0F, -1F, 1F, 1F, 2F, new CubeDeformation(0.0205F)) // paw_right_front
				, PartPose.offset(-2.25F, -1F, -2F));
		PartDefinition paw_right_back = body.addOrReplaceChild("paw_right_back", CubeListBuilder.create()
				.texOffs(184, 0).addBox(-0.5F, 0F, -1F, 1F, 1F, 2F, new CubeDeformation(0.021F)) // paw_right_back
				, PartPose.offset(-2.25F, -1F, 4F));
		PartDefinition tail_0 = body.addOrReplaceChild("tail_0", CubeListBuilder.create()
				.texOffs(192, 0).addBox(-0.5F, -0.5F, -1F, 1F, 1F, 3F, new CubeDeformation(0.0215F)) // tail_0
				, PartPose.offset(0F, -1.25F, 10F));
		PartDefinition tail_1 = body.addOrReplaceChild("tail_1", CubeListBuilder.create()
				.texOffs(202, 0).addBox(-0.5F, -0.5F, -1F, 1F, 1F, 3F, new CubeDeformation(0.022F)) // tail_1
				, PartPose.offset(0F, -1.25F, 12.5F));
		PartDefinition tail_2 = body.addOrReplaceChild("tail_2", CubeListBuilder.create()
				.texOffs(212, 0).addBox(-0.5F, -0.5F, -1F, 1F, 1F, 3F, new CubeDeformation(0.0225F)) // tail_2
				, PartPose.offset(0F, -1.25F, 15F));
        return LayerDefinition.create(mesh, 256, 256);
    }
}
