package net.tabor.seedcity.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Generated by tools/build_sentinel_assets.py; edit the source, then regenerate. */
public final class SentinelMesh {
    private SentinelMesh() {}
    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
		PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
				, PartPose.offset(0F, 24F, 0F));
		PartDefinition torso = body.addOrReplaceChild("torso", CubeListBuilder.create()
				.texOffs(0, 0).addBox(-5F, -1F, -4.05F, 10F, 12F, 9F, new CubeDeformation(0.012F)) // chest_core
				.texOffs(40, 0).addBox(-5F, -1F, -5.4F, 3F, 11F, 3F, new CubeDeformation(0.0125F)) // breastplate_-5
				.texOffs(54, 0).addBox(2F, -1F, -5.4F, 3F, 11F, 3F, new CubeDeformation(0.013F)) // breastplate_2
				.texOffs(68, 0).addBox(-4F, -2F, -4.05F, 8F, 2F, 8F, new CubeDeformation(0.0135F)) // collar
				.texOffs(102, 0).addBox(-2F, -5F, -2.7F, 4F, 4F, 5F, new CubeDeformation(0.014F)) // neck_joint
				.texOffs(122, 0).addBox(-4F, 0F, 4.05F, 8F, 10F, 3F, new CubeDeformation(0.0145F)) // back_plate
				.texOffs(146, 0).addBox(-1F, 1F, 5.67F, 2F, 8F, 1F, new CubeDeformation(0.015F)) // spine
				.texOffs(154, 0).addBox(-1F, 1F, -5.535F, 2F, 1F, 1F, new CubeDeformation(0.0155F)) // signal_0
				.texOffs(162, 0).addBox(-1F, 3.5F, -5.535F, 2F, 1F, 1F, new CubeDeformation(0.016F)) // signal_1
				.texOffs(170, 0).addBox(-1F, 6F, -5.535F, 2F, 1F, 1F, new CubeDeformation(0.0165F)) // signal_2
				.texOffs(178, 0).addBox(-1F, 8.5F, -5.535F, 2F, 1F, 1F, new CubeDeformation(0.017F)) // signal_3
				.texOffs(186, 0).addBox(-5F, 10F, -4.05F, 10F, 2F, 9F, new CubeDeformation(0.0175F)) // belt
				, PartPose.offset(0F, -31F, 0F));
		PartDefinition head = torso.addOrReplaceChild("head", CubeListBuilder.create()
				.texOffs(0, 23).addBox(-3.5F, -8F, -5.4F, 7F, 8F, 11F, new CubeDeformation(0.018F)) // helmet
				.texOffs(38, 23).addBox(-3F, -4F, -5.508F, 6F, 2F, 1F, new CubeDeformation(0.0185F)) // visor
				.texOffs(54, 23).addBox(-3.5F, -5F, -5.562F, 7F, 1F, 1F, new CubeDeformation(0.019F)) // brow
				.texOffs(72, 23).addBox(-2.5F, -3.8F, -5.643F, 1F, 1F, 1F, new CubeDeformation(0.0195F)) // eye_right
				.texOffs(78, 23).addBox(1.5F, -3.8F, -5.643F, 1F, 1F, 1F, new CubeDeformation(0.02F)) // eye_left
				.texOffs(84, 23).addBox(-3F, -2F, -5.508F, 6F, 2F, 1F, new CubeDeformation(0.0205F)) // face_plate
				.texOffs(100, 23).addBox(-1F, -3.5F, -7.02F, 2F, 3F, 3F, new CubeDeformation(0.021F)) // nose
				.texOffs(112, 23).addBox(-1F, -7F, -5.562F, 2F, 2F, 1F, new CubeDeformation(0.0215F)) // forehead_plate
				, PartPose.offset(0F, -3F, 0F));
		PartDefinition right_arm = torso.addOrReplaceChild("right_arm", CubeListBuilder.create()
				.texOffs(120, 23).addBox(-2.5F, -1F, -4.05F, 5F, 5F, 8F, new CubeDeformation(0.022F)) // right_shoulder
				.texOffs(148, 23).addBox(-1.5F, 4F, -2.025F, 3F, 5F, 4F, new CubeDeformation(0.0225F)) // right_upper_arm
				.texOffs(164, 23).addBox(-2F, 8F, -2.7F, 4F, 2F, 5F, new CubeDeformation(0.023F)) // right_elbow
				.texOffs(184, 23).addBox(-2.5F, 10F, -3.375F, 5F, 5F, 7F, new CubeDeformation(0.0235F)) // right_gauntlet
				.texOffs(210, 23).addBox(-0.5F, 11F, -3.645F, 1F, 3F, 1F, new CubeDeformation(0.024F)) // right_arm_signal
				.texOffs(216, 23).addBox(-2F, 15F, -2.7F, 4F, 3F, 5F, new CubeDeformation(0.0245F)) // right_fist
				, PartPose.offset(-7F, 0F, 0F));
		PartDefinition left_arm = torso.addOrReplaceChild("left_arm", CubeListBuilder.create()
				.texOffs(0, 44).addBox(-2.5F, -1F, -4.05F, 5F, 5F, 8F, new CubeDeformation(0.025F)) // left_shoulder
				.texOffs(28, 44).addBox(-1.5F, 4F, -2.025F, 3F, 5F, 4F, new CubeDeformation(0.0255F)) // left_upper_arm
				.texOffs(44, 44).addBox(-2F, 8F, -2.7F, 4F, 2F, 5F, new CubeDeformation(0.026F)) // left_elbow
				, PartPose.offset(7F, 0F, 0F));
		PartDefinition left_forearm = left_arm.addOrReplaceChild("left_forearm", CubeListBuilder.create()
				.texOffs(64, 44).addBox(-2.5F, 2F, -3.375F, 5F, 5F, 7F, new CubeDeformation(0.0265F)) // left_gauntlet
				.texOffs(90, 44).addBox(-0.5F, 3F, -3.645F, 1F, 3F, 1F, new CubeDeformation(0.027F)) // left_arm_signal
				.texOffs(96, 44).addBox(-2F, 7F, -2.7F, 4F, 3F, 5F, new CubeDeformation(0.0275F)) // left_fist
				, PartPose.offset(0F, 8F, 0F));
		PartDefinition right_leg = body.addOrReplaceChild("right_leg", CubeListBuilder.create()
				.texOffs(116, 44).addBox(-2F, 0F, -2.7F, 4F, 8F, 5F, new CubeDeformation(0.028F)) // right_thigh
				.texOffs(136, 44).addBox(-2.5F, 0F, -3.375F, 5F, 4F, 7F, new CubeDeformation(0.0285F)) // right_hip_plate
				.texOffs(162, 44).addBox(-1.5F, 8F, -2.7F, 3F, 2F, 5F, new CubeDeformation(0.029F)) // right_knee
				.texOffs(180, 44).addBox(-0.5F, 8F, -2.97F, 1F, 2F, 1F, new CubeDeformation(0.0295F)) // right_knee_light
				.texOffs(186, 44).addBox(-2F, 10F, -2.7F, 4F, 6F, 5F, new CubeDeformation(0.03F)) // right_shin
				.texOffs(206, 44).addBox(-2.5F, 16F, -4.05F, 5F, 3F, 8F, new CubeDeformation(0.0305F)) // right_boot
				, PartPose.offset(-3F, -19F, 0F));
		PartDefinition left_leg = body.addOrReplaceChild("left_leg", CubeListBuilder.create()
				.texOffs(234, 44).addBox(-2F, 0F, -2.7F, 4F, 8F, 5F, new CubeDeformation(0.031F)) // left_thigh
				.texOffs(0, 59).addBox(-2.5F, 0F, -3.375F, 5F, 4F, 7F, new CubeDeformation(0.0315F)) // left_hip_plate
				.texOffs(26, 59).addBox(-1.5F, 8F, -2.7F, 3F, 2F, 5F, new CubeDeformation(0.032F)) // left_knee
				.texOffs(44, 59).addBox(-0.5F, 8F, -2.97F, 1F, 2F, 1F, new CubeDeformation(0.0325F)) // left_knee_light
				.texOffs(50, 59).addBox(-2F, 10F, -2.7F, 4F, 6F, 5F, new CubeDeformation(0.033F)) // left_shin
				.texOffs(70, 59).addBox(-2.5F, 16F, -4.05F, 5F, 3F, 8F, new CubeDeformation(0.0335F)) // left_boot
				, PartPose.offset(3F, -19F, 0F));
		PartDefinition spear = left_forearm.addOrReplaceChild("spear", CubeListBuilder.create()
				.texOffs(98, 59).addBox(-0.5F, -23F, -0.75F, 1F, 42F, 1F, new CubeDeformation(0.034F)) // spear_shaft
				.texOffs(104, 59).addBox(-0.75F, -23F, -1F, 2F, 2F, 2F, new CubeDeformation(0.0345F)) // spear_pommel
				.texOffs(114, 59).addBox(-1.5F, -32F, -1.25F, 3F, 9F, 2F, new CubeDeformation(0.035F)) // spear_head
				.texOffs(126, 59).addBox(-0.5F, -35F, -1.25F, 1F, 3F, 2F, new CubeDeformation(0.0355F)) // spear_tip
				.texOffs(134, 59).addBox(-0.5F, -31F, -1.45F, 1F, 7F, 1F, new CubeDeformation(0.036F)) // spear_channel
				, PartPose.offset(0F, 8F, 0F));
        return LayerDefinition.create(mesh, 256, 256);
    }
}
